server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: lamlam276762
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt: {
  signerKey: "tvldt/yAkVypVVaOP8P6EhtCsrbIqavnBd5Xox+yvuVBVT1OX4O33SKFVHbanHbL",
  valid-duration: 3600, #In second
  refreshable-duration: 36000 #In second
}